# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# Note: [dependency-groups] will only get updated if there is an update in dependencies

version: 2
updates:
  - package-ecosystem: "uv" 
    directory: "/worker"
    schedule:
      interval: "cron"
      cronjob: "0 0 1 * *"   
    cooldown:
      default-days: 7
    # ignore requirements-dev.txt
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "argus"
    groups:
      all-dependencies:
        patterns: ["*"]
  - package-ecosystem: "uv" 
    directory: "/api"
    schedule:
      interval: "cron"
      cronjob: "0 0 1 * *"  
    cooldown:
      default-days: 7
    groups:
      all-dependencies:
        patterns: ["*"]
