services:

  # ──────────────────────────────────────────────────────────────
  # 2. JIVE Ingress: Webhook Handler
  # ──────────────────────────────────────────────────────────────
  jive-ingress:
    build:
      context: ../
      dockerfile: jive/api/Dockerfile
    container_name: jive-api
    ports:
      - "8000:8000"


  # ──────────────────────────────────────────────────────────────
  # 3. JIVE Worker: Queue Consumer
  # ──────────────────────────────────────────────────────────────
  jive-worker:
    build:
      context: ../
      dockerfile: jive/worker/Dockerfile
    container_name: jive-worker
    command: [ "python", "worker.py" ]


