name: Publish Release

on:
  workflow_dispatch:
    types: [manual-trigger]
    inputs:
      jive_release_tag:
        description: 'Release tag in format "vYYYY.MM.DD.XX"'
        required: true
        type: string
      deploy_argus:
        description: 'Make an Arugs release'
        required: true
        type: boolean
      argus_release_tag:
        description: 'Release tag in format "vYYYY.MM.DD.XX".'
        required: true
        type: string
      deploy_argus_schemas:
        description: 'Make an Arugs schemas release'
        required: true
        type: boolean
      argus_schemas_release_tag:
        description: 'Release tag in format "vYYYY.MM.DD.XX".'
        required: true
        type: string

permissions:
  contents: write

jobs:
  publish_argus_schemas:
      if: ${{ inputs.deploy_argus_schemas }} 
      runs-on: ubuntu-latest
      steps:
        - name: Trigger argus_schemas workflow
          uses: peter-evans/repository-dispatch@v4
          with:
            token: ${{ secrets.REPO_DISPATCH_TOKEN }}  
            repository: impact-initiatives/argus_schemas
            event-type: manual-release
            client-payload: '{"release_tag": "${{ inputs.argus_schemas_release_tag }}"}'

  publish_argus:
    if: ${{ inputs.deploy_argus }} 
    needs: publish_argus_schemas
    runs-on: ubuntu-latest
    steps:
        - name: Trigger argus workflow
          uses: peter-evans/repository-dispatch@v4
          with:
            token: ${{ secrets.REPO_DISPATCH_TOKEN }}  
            repository: impact-initiatives/argus
            event-type: manual-release
            client-payload: '{"release_tag": "${{ inputs.argus_release_tag }}"}'

  publish_jive:
    needs: publish_argus
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6  

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ inputs.jive_release_tag }}
          name: ${{ inputs.jive_release_tag }}
          generate_release_notes: true

      - name: Trigger acr deployments
        uses: peter-evans/repository-dispatch@v4
        with:
          event-type: post-release-processing