name: Publish Release

# Jive and argus are deployed together so can share the same release tag.
# argus schemas can be released independently so can possibly have
# its own different release tag (likely only if it released twice
# in one day)

on:
  workflow_dispatch:
    types: [manual-trigger]
    inputs:
      release_tag:
        description: '"Jive" and "Argus" release tag in format "YYYYMMDDXX" .'
        required: true
        type: string
      release_jive:
        description: 'Publish a "Jive" release.'
        required: true
        type: boolean
      release_argus:
        description: 'Publish an "Arugs" release.'
        required: true
        type: boolean
      deploy_jive:
        description: 'Create Jive container app revision.'
        required: true
        type: boolean
      release_argus_schemas:
        description: 'Publish an "Arugs Schemas" release.'
        required: true
        type: boolean
      argus_schemas_release_tag:
        description: '"Argus Schemas" release tag in format "YYYYMMDDXX".'
        required: true
        type: string
      release_type:
        description: 'Type of release.'
        required: true
        # type: environment need admin to create these
        type: choice
        options:
          - dev
          - test
          - prod

permissions:
  contents: write

jobs:
  
  create_argus_schemas_release:
      if: ${{ inputs.release_argus_schemas }} 
      runs-on: ubuntu-latest
      steps:
        - name: Trigger argus_schemas workflow
          uses: peter-evans/repository-dispatch@v4
          with:
            token: ${{ secrets.REPO_DISPATCH_TOKEN }}  
            repository: impact-initiatives/argus_schemas
            event-type: manual-release
            client-payload: '{"release_tag": "${{ inputs.argus_schemas_release_tag }}"}'

  create_argus_release:
    if: ${{ inputs.release_argus }} 
    runs-on: ubuntu-latest
    steps:
        - name: Trigger argus workflow
          uses: peter-evans/repository-dispatch@v4
          with:
            token: ${{ secrets.REPO_DISPATCH_TOKEN }}  
            repository: impact-initiatives/argus
            event-type: manual-release
            client-payload: '{"release_tag": "${{ inputs.release_tag }}"}'

  create_jive_release:
    needs: create_argus_release
    if: ${{ inputs.release_jive && ( always() &&  (needs.create_argus_release.result == 'success' || needs.create_argus_release.result == 'skipped' ))}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6  

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ inputs.release_tag }}
          name: ${{ inputs.release_tag }}
          generate_release_notes: true

  build_and_push_jive_worker_images:
    needs: create_jive_release
    if: ${{ always() && needs.create_jive_release.result == 'success' }}
    uses: impact-initiatives/jive/.github/workflows/push_to_azure_acr.yml@main
    with:
      release_tag: ${{ inputs.release_tag }}
      acr_name: acrimpact
      image_name: jive-worker
      # release_type: ${{ inputs.release_type }}
      build_context: ./worker
    secrets:
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

  create_container_app_revision_worker:
    needs: build_and_push_jive_worker_images
    if: ${{ inputs.deploy_jive && always() && ( needs.build_and_push_jive_worker_images.result == 'success' || needs.build_and_push_jive_worker_images.result == 'skipped')}}
    uses: impact-initiatives/jive/.github/workflows/push_to_azure_containerapp.yml@main
    with:
      release_tag: ${{ inputs.release_tag }}
      acr_name: acrimpact
      image_name: jive-worker
      # release_type: ${{ inputs.release_type }}
      container_app_name: jive-worker
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  build_and_push_jive_api_images:
    needs: create_jive_release
    if: ${{ always() && needs.create_jive_release.result == 'success' }}
    uses: impact-initiatives/jive/.github/workflows/push_to_azure_acr.yml@main
    with:
      release_tag: ${{ inputs.release_tag }}
      acr_name: acrimpact
      image_name: jive-api
      # release_type: ${{ inputs.release_type }}
      build_context: ./api
    secrets:
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

  create_container_app_revision_api:
    needs: build_and_push_jive_api_images
    if: ${{ inputs.deploy_jive && always() && (needs.build_and_push_jive_api_images.result == 'success' || needs.build_and_push_jive_api_images.result == 'skipped')}}
    uses: impact-initiatives/jive/.github/workflows/push_to_azure_containerapp.yml@main
    with:
      release_tag: ${{ inputs.release_tag }}
      acr_name: acrimpact
      image_name: jive-api
      # release_type: ${{ inputs.release_type }}
      container_app_name: jive-api
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
    
