name: Publish Release

# Jive and argus are deployed together so can share the same release tag.
# argus schemas can be released independently so can possibly have
# its own different release tag (likely only if it released twice
# in one day)

on:
  workflow_dispatch:
    types: [manual-trigger]
    inputs:
      release_tag:
        description: '"Jive" and "Argus" release tag in format "vYYYY.MM.DD.XX" .'
        required: true
        type: string
      release_argus:
        description: 'Publish an "Arugs" release.'
        required: true
        type: boolean
      release_argus_schemas:
        description: 'Publish an "Arugs Schemas" release.'
        required: true
        type: boolean
      argus_schemas_release_tag:
        description: '"Argus Schemas" release tag in format "vYYYY.MM.DD.XX".'
        required: true
        type: string
      release_type:
        description: 'Type of release.'
        required: true
        type: environment

env:
  ACR_NAME: acrimpact
  WORKER_IMAGE_NAME: jive-worker
  # WORKER_CONTAINER_APP_NAME: jive-worker
  API_IMAGE_NAME: jive-api
  # API_CONTAINER_APP_NAME: jive-ingress

permissions:
  contents: write

jobs:
  create_argus_schemas_release:
      if: ${{ inputs.release_argus_schemas }} 
      runs-on: ubuntu-latest
      steps:
        - name: Trigger argus_schemas workflow
          uses: peter-evans/repository-dispatch@v4
          with:
            token: ${{ secrets.REPO_DISPATCH_TOKEN }}  
            repository: impact-initiatives/argus_schemas
            event-type: manual-release
            client-payload: '{"release_tag": "${{ inputs.argus_schemas_release_tag }}"}'

  create_argus_release:
    needs: create_argus_schemas_release
    if: ${{ always() && inputs.release_argus && (needs.create_argus_schemas_release.result == 'success' || needs.create_argus_schemas_release.result == 'skipped') }}    
    runs-on: ubuntu-latest
    steps:
        - name: Trigger argus workflow
          uses: peter-evans/repository-dispatch@v4
          with:
            token: ${{ secrets.REPO_DISPATCH_TOKEN }}  
            repository: impact-initiatives/argus
            event-type: manual-release
            client-payload: '{"release_tag": "${{ inputs.release_tag }}"}'

  create_jive_release:
    needs: create_argus_release
    if: ${{ always() &&  needs.create_argus_release.result == 'success' || needs.create_argus_release.result == 'skipped' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6  

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ inputs.release_tag }}
          name: ${{ inputs.release_tag }}
          generate_release_notes: true

  build_and_push_jive_worker_images:
    needs: create_jive_release
    if: ${{ always() && needs.create_jive_release.result == 'success' }}
    uses: inpact-initiatives/jive/.github/workflows/deploy_to_azure.yml
    with:
      release_tag: ${{ inputs.release_tag }}
      acr_name: ${{ env.ACR_NAME }}
      image_name: ${{ env.WORKER_IMAGE_NAME }}
      release_type: ${{ inputs.release_type }}
      # container_app_name: ${{ env.WORKER_CONTAINER_APP_NAME }}

  build_and_push_jive_api_images:
    needs: create_jive_release
    if: ${{ always() && needs.create_jive_release.result == 'success' }}
    uses: inpact-initiatives/jive/.github/workflows/deploy_to_azure.yml
    with:
      release_tag: ${{ inputs.release_tag }}
      acr_name: ${{ env.ACR_NAME }}
      image_name: ${{ env.API_IMAGE_NAME }}
      release_type: ${{ inputs.release_type }}
      # container_app_name: ${{ env.API_CONTAINER_APP_NAME }}
    
    # runs-on: ubuntu-latest
    # steps:
    #   - name: Trigger acr deployments
    #     uses: peter-evans/repository-dispatch@v4
    #     with:
    #       event-type: post-release-processing