name: Run Api ruff check
on: 
  push:
    paths:
      - 'worker/**'
  pull_request:
    paths:
      - 'worker/**'
jobs:
  ruff:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: "./worker"
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/ruff-action@v4
      - run: ruff format .
      - run: ruff check . --fix
      - run: ruff format .
      - uses: EndBug/add-and-commit@v10
        with: 
          default_author: github_actions
          committer_name: GitHub Actions
          committer_email: actions@github.com
          message: 'Auto-format code'
          push: true